vision:
  ballhsv:
    h0: 0
    h1: 180
    s0: 0
    s1: 115
    v0: 110
    v1: 255
  calib:
    filePath: /nimbro/share/launch/config/vision/cCFile.yml
  camera:
    devNumber: 0
    flipHor: 0
    flipVer: 0
    heightUnDistortion: 1177
    useBagfile: 1
    widthUnDistortion: 1620
  dataAssociation:
    MaxAngDiff: 71
    MaxErrorForInlier: 25
    _MaxAngleChange: 25
    _MinCompLengthForModelError: 30
  debug:
    publishTime: 0
    saveProcessingTime: 0
    saveTrajectory: 0
    showAssociateLines: 0
    showBoundingRects: 1
    showCamPose: 0
    showCorrespondence: 1
    showFieldHull: 1
    showFieldModel: 0
    showHoughLines: 0
    showLineInfo: 0
    showMarkers: 1
    showMergedLines: 0
    showModelLines: 1
    showNodeGraph: 1
    showRobPose: 1
    showSkeletonPixels: 1
    showTangentLine: 0
    showTrajectory: 1
    useKalmanFilter: 1
    useMotionOdom: 1
    useParticleFilter: 0
    useRansac: 0
    useSolvePnP: 1
    useSolvePnPRansac: 1
    visTrajectoryData: 0
  field:
    BonnField: 1
    FieldBorder: 9
    MaxDistanceFromBottomOfImage: 200
    maxContourCount: 3
    minArea: 600
  fieldhsv:
    h0: 37
    h1: 90
    s0: 85
    s1: 255
    v0: 20
    v1: 120
  goal:
    DistanceToMerge: 20
    MaxOutField: 40
    MinLineLength: 30
    VoteDouble: 18
    cannyThreadshold: 21
    dilate: 0
    erode: 0
    jumpMax: 25
    minContinuesColor: 10
    minDoubleLength: 3
    minEdgeValue: 100
  goalhsv:
    h0: 24
    h1: 126
    s0: 0
    s1: 255
    v0: 120
    v1: 255
  graphNode:
    AngleToMerge: 0
    DistanceCompToMerge: 0
    LineWidth: 6
    MaxDist: 0
    MaxDistanceForMergeNode1: 50
    MaxDistanceForMergeNode2: 50
    MaxLineSegDistance: 30
    MaxLineSegDistanceForJoint: 400
    MaxProjectedDistance: 15
    MergeJointDist: 0
    MinCmpLineLength: 0
    MinDist: 1000
    MinDistForMerge: 30
    Min_adj: 5
    SamplePointDist: 3
    SmallAngle: 15
    _AvgAngleDiff: 6
    _MaxAngleDiff: 5
    _MaxAvgProjectedDistance: 20
    _MaxCloseNum: 4
    _MaxDistanceForConnect: 7
    _MaxDistanceForMerge: 90
    _MaxLineSegDistance: 30
    _MaxProjectedDistance: 10
    _MinAngle: 42
    _MinAngleForSameComp: 165
    _MinCmpLineLength: 15
    _Min_adj: 31
    _NeighborRadius: 12
  hillclimbing:
    ErrorThreshold1: 1
    ErrorThreshold2: 25
    HeadingOffset: 0
    MaxHypothesisNum: 31
    MaxIterationNum: 4
    MovingStepCoefficient: 0.05
  icp:
    AvgDistThresholdForConf: 3
    HeadingOffset: 3.1416
    IcpInlierDistThreshold: 4912
    InlierNumThresholdForConf: 30
    KFOrientationCov: 10000
    KFPositionCov: 10000
    SamplePointDist_WorldCord: 0.2
  kalmanFilter:
    ErrorThreshod: 5
    KFOrientationCov: 1000000
    KFPositionCov: 1000000
  line:
    AngleToMerge: 5
    AngleToMergeImg: 0
    Div1: 0.5
    Div2: 0.7
    HoughLineMinLineLength: 3
    HoughLineRho: 7
    HoughLineTheta: 6
    HoughLineVoteThreshold: 14
    HoughLinemaxLineGap: 40
    LocalOptimalRange: 3
    MaxNeighborDist: 3
    MaxPointLineDistance: 100
    MeasAreaThreshod: 60000
    MeasLineLengthThreshod: 200
    MeasLineMaxAngDifThreshod: 60
    MeasLineNumThreshod: 4
    MinBrightnessValue: 79
    MinLineLength: 70
    MinLineSegDistance: 0.8
    MinLineSegDistanceImg: 50
    MinProjectedDistance: 0.35
    MinProjectedDistanceImg: 23
    MinSkeletonValue: 41
    ObstacleLineDistance: -10
  linehsv:
    h0: 0
    h1: 180
    s0: 11
    s1: 255
    v0: 0
    v1: 254
  location:
    x: -1.42
    y: 0
    z: 0.54
  obstacle:
    minArea: 300
  obstaclehsv:
    h0: 100
    h1: 180
    s0: 22
    s1: 255
    v0: 0
    v1: 255
  orientation:
    x: 0
    y: 0
    z: 0
  particleFilter:
    HeadingOffset: 0
    MinSumOfLineLengthOnImage: 100
    ParticleNum: 200
    RandomSamplePct: 0.2
  projection:
    timeToShift: 0.150
  square:
    MaxNeighborDist: 2
    Max_K: 9
    Max_K_border: 5
    MinPointNum: 0
