vision:
  ballhsv:
    h0: 0
    h1: 180
    s0: 0
    s1: 114
    v0: 107
    v1: 255
  calib:
    filePath: /nimbro/share/launch/config/vision/cCFile.yml
  camera:
    devNumber: 0
    flipHor: 0
    flipVer: 0
    heightUnDistortion: 1177
    useBagfile: 1
    widthUnDistortion: 1620
  dataAssociation:
    MaxAngDiff: 45
    MaxErrorForInlier: 100
    _MaxAngleChange: 10
    _MinCompLengthForModelError: 100
  debug:
    publishTime: 1
    showAssociateLines: 1
    showBoundingRects: 1
    showCamPose: 1
    showCorrespondence: 1
    showFieldHull: 1
    showFieldModel: 1
    showHoughLines: 1
    showLineInfo: 0
    showMarkers: 1
    showMergedLines: 1
    showModelLines: 1
    showNodeGraph: 1
    showRobPose: 1
    showSkeletonPixels: 1
    showTangentLine: 1
    useKalmanFilter: 1
    useMotionOdom: 0
    useParticleFilter: 0
    useRansac: 0
    useSolvePnP: 0
  field:
    BonnField: 0
    FieldBorder: 4
    MaxDistanceFromBottomOfImage: 200
    maxContourCount: 4
    minArea: 600
  fieldhsv:
    h0: 21
    h1: 84
    s0: 111
    s1: 225
    v0: 0
    v1: 137
  goal:
    DistanceToMerge: 20
    MaxOutField: 40
    MinLineLength: 40
    VoteDouble: 31
    cannyThreadshold: 35
    dilate: 0
    erode: 0
    jumpMax: 28
    minContinuesColor: 20
    minDoubleLength: 2
    minEdgeValue: 100
  goalhsv:
    h0: 70
    h1: 120
    s0: 20
    s1: 100
    v0: 126
    v1: 255
  graphNode:
    AngleToMerge: 20
    DistanceCompToMerge: 100
    LineWidth: 19
    MaxDist: 400
    MaxDistanceForMergeNode1: 64
    MaxDistanceForMergeNode2: 64
    MaxLineSegDistance: 50
    MaxProjectedDistance: 30
    MergeJointDist: 1000
    MinCmpLineLength: 10
    MinDistForMerge: 1000
    Min_adj: 40000
    SamplePointDist: 5
    SmallAngle: 60
    _AvgAngleDiff: 15
    _MaxAngleDiff: 15
    _MaxAvgProjectedDistance: 25
    _MaxCloseNum: 10
    _MaxDistanceForConnect: 40
    _MaxDistanceForMerge: 80
    _MaxLineSegDistance: 100
    _MaxProjectedDistance: 25
    _MinAngle: 45
    _MinAngleForSameComp: 165
    _MinCmpLineLength: 20
    _Min_adj: 100
    _NeighborRadius: 15
  hillclimbing:
    ErrorThreshold1: 5
    ErrorThreshold2: 50
    HeadingOffset: 0
    MaxHypothesisNum: 20
    MaxIterationNum: 5
    MovingStepCoefficient: 1
  icp:
    AvgDistThresholdForConf: 40
    HeadingOffset: 3.14159
    IcpInlierDistThreshold: 60000
    InlierNumThresholdForConf: 50
    KFOrientationCov: 0.1
    KFPositionCov: 0.1
    SamplePointDist_WorldCord: 0.1
  kalmanFilter:
    ErrorThreshod: 5
    KFOrientationCov: 1000000
    KFPositionCov: 1000000
  line:
    AngleToMerge: 15
    AngleToMergeImg: 10
    Div1: 0.5
    Div2: 0.8
    HoughLineMinLineLength: 50
    HoughLineRho: 10
    HoughLineTheta: 10
    HoughLineVoteThreshold: 20
    HoughLinemaxLineGap: 65
    LocalOptimalRange: 0
    MaxPointLineDistance: 60
    MeasAreaThreshod: 50000
    MeasLineLengthThreshod: 300
    MeasLineMaxAngDifThreshod: 60
    MeasLineNumThreshod: 4
    MinBrightnessValue: 30
    MinLineLength: 100
    MinLineSegDistance: 1
    MinLineSegDistanceImg: 100
    MinProjectedDistance: 0.25
    MinProjectedDistanceImg: 7
    MinSkeletonValue: 43
    ObstacleLineDistance: -40
  linehsv:
    h0: 0
    h1: 180
    s0: 11
    s1: 255
    v0: 0
    v1: 255
  location:
    x: 0
    y: 0
    z: 0.6
  obstacle:
    minArea: 300
  obstaclehsv:
    h0: 104
    h1: 180
    s0: 100
    s1: 255
    v0: 44
    v1: 75
  orientation:
    x: 0
    y: 0
    z: 0
  particleFilter:
    HeadingOffset: 0
    MinSumOfLineLengthOnImage: 100
    ParticleNum: 0
    RandomSamplePct: 0.2
  projection:
    timeToShift: 0.15
  square:
    MaxNeighborDist: 5
    Max_K: 6
    Max_K_border: 5
    MinPointNum: 3
